// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB39x_4HGRI9i1KtIaetBAl29KhKMvHw_s',
    appId: '1:107791955698:web:9be8bed78a9a7810c8826b',
    messagingSenderId: '107791955698',
    projectId: 'mobile2unid',
    authDomain: 'mobile2unid.firebaseapp.com',
    storageBucket: 'mobile2unid.appspot.com',
    measurementId: 'G-KHG3V8623H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4q_C2rfArBWkG22IzSztAG1OpZnRDKpE',
    appId: '1:107791955698:android:a20f14e7cc8643e7c8826b',
    messagingSenderId: '107791955698',
    projectId: 'mobile2unid',
    storageBucket: 'mobile2unid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Ebuylbd9Rs0fiRLhL-IlmF59YV6YquU',
    appId: '1:107791955698:ios:381e901856d8226fc8826b',
    messagingSenderId: '107791955698',
    projectId: 'mobile2unid',
    storageBucket: 'mobile2unid.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
